### ISSUE TITLE
MCQ: action after clicking a choice

### ISSUE THREAD

**Issue by martin-henz** [source-academy/grader#17]
<img width="1440" alt="saved" src="https://user-images.githubusercontent.com/30220768/43886695-24ee1f26-9bef-11e8-8d38-b51460dcd0a0.png">

Currently, there is an empty colored box (orange for wrong answer, green for right answer) popping up, in addition to the "Saved" box.

**Comment by remo5000** [comment]
Hi Prof @martin-henz , is this running off the docker image?

**Comment by ningyuansg** [comment]
This is probably because empty hints (not sure if empty string or null) are not being handled correctly on the frontend.

/move to cadet-frontend
