### ISSUE TITLE
Trying choices in MCQ until hitting the correct answer

### ISSUE THREAD

**Issue by martin-henz** [source-academy/grader#18]
Currently, a student seems to be able to try again, after choosing the wrong answer. They will of course try the choices until they hit the correct one, and then press "next".

That's actually fine for paths. But if that's the case, perhaps "next" should not be possible until the student has found the correct answer.

**Comment by remo5000** [comment]
@martin-henz This option, and the indication that the MCQ is correct, only occurs for questions with a definite solution (i.e this mcq is ungraded). If there is no solution, then the options can be selected without any hints.

![image](https://user-images.githubusercontent.com/12512488/43938348-b481aad0-9c95-11e8-93bf-e9f62ddeb5a6.png)

In fact, the student can go on to do other questions, just as how a student might skip a programming question until later.

**Comment by ningyuansg** [comment]
This behaviour is client-side (on the browser) and does not reach the grader, so I'll move this to the frontend repo.

Agree that hiding the next button is a good feature.

/move to cadet-frontend

**Comment by ningyuansg** [comment]
good bot

**Comment by remo5000** [comment]
Whoops, didn't see the repo 😅
