### ISSUE TITLE
Programming problems in paths

### ISSUE THREAD

**Issue by martin-henz** [source-academy/grader#19]
It would be nice if paths could support programming problems. The testing would not have to be done in the cloud (using lambda), but could just be done in the browser, but using the same GRADER syntax.  I'd suggest a single GRADER. When the grader returns maxgrade, the answer is deemed correct, and otherwise incorrect.

**Comment by geshuming** [comment]
Added autograding tab to frontend, it should be possible to write test cases for Paths and students run test cases in the frontend.
