### ISSUE TITLE
Add a parameter, globals, to the grader API

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/grader#7]
The grader currently works fine for 'native' source programs, but not for those that use external libraries such as runes, curves, or sound. This is not a trivial limitation as the nodejs environment in which the grader runs do not support the external library files themselves, which were written for the browser.

In order to grade source programs using these external libraries, we should allow the parameter *'globals'* as described in https://github.com/source-academy/cadet/issues/149. Globals is a map of a string identifier to a javascript value. With this, module staff should be able to redefine special versions of external library functions which are executable in the nodejs environment, allowing us to grade source programs using external libraries.

The idea is that since most runes, curves, and sound missions are mathematical in their logic, that the newly defined functions in globals will be able to abstract runes, curves, and sound into a number array. Then, the grader programs need only check that the numbers are equal.

**Comment by ningyuansg** [comment]
Or use https://github.com/stackgl/headless-gl for runes.

**Comment by martin-henz** [comment]
Agree. Can we have a how-to, for the authors of grader programs? I've started an avenger handbook. This can be part of it, or the handbook can point to a readme for authors of grader programs.

**Comment by ningyuansg** [comment]
I'll prioritize writing the API reference in this repository's README first. If possible, I think that guides should stay as close to the repositories as possible (i.e. checked into repository or contained in the README).

If in a separate file, there is a good chance that someone in the future would update this repository without updating the guide, causing the guide to be outdated.
