### ISSUE TITLE
Add support for runes library

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/grader#9]
In general,

```
runes ----(functions)----> modified_runes
```

I see two ways of grading runes.

### Checking the end product (modified_runes)
- Use something like [headless-gl](https://github.com/stackgl/headless-gl) to provide a webGL api for the AWS lambda node environment.
- Expose this library to the grader program
- The grader program is then able to check buffers generated by the student programs versus whatever they want, and award marks accordingly

**Pros**
- No magic, staff have control over what is happening, since the comparison happens in the grader programs
- Grade API remains largely unchanged and therefore consistent among assessments

**Cons**
- Not an elegant solution. There is also the chance that some rune functions are not commutative, i.e. perhaps `quarter_turn_right(my_rune)` and `quarter_turn_left(quarter_turn_left(quarter_turn_left(my_rune)))` do not generate the same end product
- Staff must learn and manage another api
- Not an elegant solution

### Checking the steps (functions)
- Using something like [acorn](https://github.com/acornjs/acorn), which is already a sub-dependency of js-slang, we generate the AST of the student program and parse it into a series of function calls.
- The grader simplifies this series of function calls according to a set of rules that we define here
- The grader program provides an example of a solution; this to is simplified
- The simplified student and grader series of function calls are compared. Marks are awarded if they match.

Below, `const right = quarter_turn_right; const left = quarter_turn_left;`. For example, the student writes,

```javascript
function upside_down(rune) {
    const theRune = rune;
    const runeTurned = right(theRune);
    const huh = left(left(left(runeTurned)));
    return huh
}
```

And the grader program is,

```javascript
const upside_down = rune => right(right(rune));
```

We define the set of rules,
- Compare functions of the same name
- Of these functions, compare their return values
- Of the return values, only our defined rune functions, and the function parameter is allowed
- `(r) => left(r)` is the same as `(r) => right(right(right(r)))`

Then, the grader program compares:

```javascript
// Compare functions of the same name
STUDENT: upside_down
GRADER: upside_down
// Compare their return values
STUDENT: huh
GRADER: right(right(rune))
// Only defined rune functions and function parameters allowed (resolve references)
STUDENT: left(left(left(runeTurned)))
// Only defined rune functions and function parameters allowed (resolve references)
STUDENT: left(left(left(right(theRune))))
// Only defined rune functions and function parameters allowed (resolve references)
STUDENT: left(left(left(right(rune))))
// `(r) => left(r)` is the same as `(r) => right(right(right(r)))`
STUDENT: right(right(rune))
GRADER: right(right(rune))
// marks awarded
```

**Pros**
- Much more elegant of a solution
- Does not depend on the behaviour of whatever node webgl substitute we use

**Cons**
- This process is abstracted away from the staff, and so they must learn and follow an API
- The grader API will be different for runes than other assessments, since the graderProgram is now not a function that returns a mark, but a function that demonstrates the correct solution
- In addition, the XML element `GRADERPROGRAM` will be required to contain a new attribute that is the mark awarded if this process completes with a match between student and grader programs
- Must spend quite a lot of time defining rules

**Comment by thenaesh** [comment]
Diving into `public/externalLibs/graphics/webGLrune.js`, we observe a function:
```
function generateFlattenedShapeList(shape) {
  var matStack = [];
  var matrix = mat4.create();
  var shape_list = {};
  function pushMat() {
    matStack.push(mat4.clone(matrix));
  }
  function popMat() {
    if (matStack.length == 0) {
      throw 'Invalid pop matrix!';
    } else {
      matrix = matStack.pop();
    }
  }
  function helper(shape, color) {
    if (shape.isPrimary) {
      if (shape.count === 0) {
        // this is blank_bb, do nothing
        return;
      }
      if (!shape_list[shape.first]) {
        shape_list[shape.first] = {
          shape: shape,
          matrices: [],
          colors: []
        };
      }
      shape_list[shape.first].matrices.push(matrix);
      shape_list[shape.first].colors.push(color || [0, 0, 0, 1]);
    } else {
      if (color === undefined && shape.getColor() !== undefined) {
        color = shape.getColor();
      }
      pushMat();
      mat4.multiply(matrix, matrix, shape.getM());
      var childShapes = shape.getS();
      for (var i = 0; i < childShapes.length; i++) {
        helper(childShapes[i], color);
      }
      popMat();
    }
  }
  function flatten(matrices, colors) {
    var instanceArray = new Float32Array(matrices.length * 20);
    for (var i = 0; i < matrices.length; i++) {
      instanceArray.set(matrices[i], 20 * i);
      instanceArray.set(colors[i], 20 * i + 16);
    }
    return instanceArray;
  }
  helper(shape);
  var flattened_shape_list = [];
  // draw a white square background first
  flattened_shape_list.push({
    shape: black_bb,
    instanceArray: new Float32Array([
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      -1,
      1,
      1,
      1,
      1,
      1
    ])
  });
  for (var key in shape_list) {
    if (shape_list.hasOwnProperty(key)) {
      var shape = shape_list[key].shape;
      var instanceArray = flatten(
        shape_list[key].matrices,
        shape_list[key].colors
      );
      flattened_shape_list.push({ shape: shape, instanceArray: instanceArray });
    }
  }
  return flattened_shape_list;
}
```

This function appears to take a rune composition (e.g. `quarter_turn_left(heart_bb)`) and construct an object containing the vertex buffer of the drawing. This function is particularly attractive because it brings no WebGL dependencies apart from a matrix library, so no dependency on `headless-gl` needs to be added.

For investigation purposes, I extended the rune library in cadet-frontend with a function `compile` to just get the JSON from `generateFlattenedShapeList` without passing it through the shape list. A rune like `heart_bb`, for instance, compiles to:
```
[{"shape":{"isPrimary":true,"first":0,"count":6},"instanceArray":{"0":1,"1":0,"2":0,"3":0,"4":0,"5":1,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0,"14":-1,"15":1,"16":1,"17":1,"18":1,"19":1}},{"shape":{"isPrimary":true,"first":276,"count":156},"instanceArray":{"0":1,"1":0,"2":0,"3":0,"4":0,"5":1,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0,"14":0,"15":1,"16":0,"17":0,"18":0,"19":1}}]
```
Some basic sanity checks pass, for instance `compile(quarter_turn_left(quarter_turn_right(heart_bb))) === compile(heart_bb)`. Some others fail, for instance `
compile(quarter_turn_left(quarter_turn_left(quarter_turn_left(heart_bb)))) === compile(quarter_turn_right(heart_bb))`. A look at the actual JSON, however reveals the following:
```
>>> compile(quarter_turn_left(quarter_turn_left(quarter_turn_left(heart_bb))));
[{"shape":{"isPrimary":true,"first":0,"count":6},"instanceArray":{"0":1,"1":0,"2":0,"3":0,"4":0,"5":1,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0,"14":-1,"15":1,"16":1,"17":1,"18":1,"19":1}},{"shape":{"isPrimary":true,"first":276,"count":156},"instanceArray":{"0":-1.8369702788777518e-16,"1":-1,"2":0,"3":0,"4":1,"5":-1.8369702788777518e-16,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0,"14":0,"15":1,"16":0,"17":0,"18":0,"19":1}}]

>>> compile(quarter_turn_right(heart_bb));
[{"shape":{"isPrimary":true,"first":0,"count":6},"instanceArray":{"0":1,"1":0,"2":0,"3":0,"4":0,"5":1,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0,"14":-1,"15":1,"16":1,"17":1,"18":1,"19":1}},{"shape":{"isPrimary":true,"first":276,"count":156},"instanceArray":{"0":6.123234262925839e-17,"1":-1,"2":0,"3":0,"4":1,"5":6.123234262925839e-17,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0,"14":0,"15":1,"16":0,"17":0,"18":0,"19":1}}]

>>> compile(stack(quarter_turn_right(heart_bb), quarter_turn_right(heart_bb)));
[{"shape":{"isPrimary":true,"first":0,"count":6},"instanceArray":{"0":1,"1":0,"2":0,"3":0,"4":0,"5":1,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0,"14":-1,"15":1,"16":1,"17":1,"18":1,"19":1}},{"shape":{"isPrimary":true,"first":276,"count":156},"instanceArray":{"0":6.123234262925839e-17,"1":-0.5,"2":0,"3":0,"4":1,"5":3.0616171314629196e-17,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0.5,"14":0,"15":1,"16":0,"17":0,"18":0,"19":1,"20":6.123234262925839e-17,"21":-0.5,"22":0,"23":0,"24":1,"25":3.0616171314629196e-17,"26":0,"27":0,"28":0,"29":0,"30":1,"31":0,"32":0,"33":-0.5,"34":0,"35":1,"36":0,"37":0,"38":0,"39":1}}]

>>> compile(quarter_turn_right(quarter_turn_right(stack(quarter_turn_left(heart_bb), quarter_turn_left(heart_bb)))));
[{"shape":{"isPrimary":true,"first":0,"count":6},"instanceArray":{"0":1,"1":0,"2":0,"3":0,"4":0,"5":1,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":0,"13":0,"14":-1,"15":1,"16":1,"17":1,"18":1,"19":1}},{"shape":{"isPrimary":true,"first":276,"count":156},"instanceArray":{"0":0,"1":-0.5,"2":0,"3":0,"4":1,"5":9.184851394388759e-17,"6":0,"7":0,"8":0,"9":0,"10":1,"11":0,"12":6.123234262925839e-17,"13":-0.5,"14":0,"15":1,"16":0,"17":0,"18":0,"19":1,"20":0,"21":-0.5,"22":0,"23":0,"24":1,"25":9.184851394388759e-17,"26":0,"27":0,"28":0,"29":0,"30":1,"31":0,"32":-6.123234262925839e-17,"33":0.5,"34":0,"35":1,"36":0,"37":0,"38":0,"39":1}}]
```

The only difference between the two is caused by what appears to be some rounding error that is easily resolved.

I'll be implementing this feature in the grader with a more comprehensive set of tests and opening a PR. Should this work with no further issues besides the rounding error, writing test cases for grading runes will be trivial: simply supply the model answer.
